### ISSUE TITLE
Thank you, it has been resolved

### ISSUE THREAD

**Issue by KeepPushingDev** [miccunifi/QualiCLIP#3]
Description:

I am reporting an issue with accessing the MICC (Media Integration and Communication Center) website and downloading the Florence 3D Faces dataset.

Details:

1. Website Access:
   - Main MICC website (http://www.micc.unifi.it/) is not accessible.
   - Error message received: "This site can't be reached. www.micc.unifi.it took too long to respond."

2. Dataset Download:
   - Specific link for the Florence 3D Faces dataset (https://www.micc.unifi.it/resources/datasets/florence-3d-faces/) is also inaccessible.
   - Unable to download or access any information about the dataset.

3. Attempts Made:
   - Tried accessing from different browsers: Chrome, Firefox, and Microsoft Edge
   - Attempted access at different times over the past two weeks
   - Checked internet connection, which is stable for other websites
   - Tried accessing through a VPN service, but still unsuccessful

4. Impact:
   - This issue is preventing research progress as the Florence 3D Faces dataset is crucial for our work in 3D face reconstruction.
   - Our team's ongoing project on advanced 3D facial modeling and analysis is currently stalled due to lack of access to this dataset.

Request:

1. Could you please check and restore access to the MICC website?
2. If the website is undergoing maintenance, could you provide an estimated time for when it will be back online?
3. Is there an alternative way to access or download the Florence 3D Faces dataset in the meantime?
4. If the dataset has been moved or is no longer available, could you please provide information on how researchers can now access it?

Additional Information:
- My location: China
- Institution: Wenzhou University, School of Computer Science and Artificial Intelligence
- Purpose: Academic research in 3D face reconstruction, specifically focusing on improving the accuracy and efficiency of 3D facial modeling techniques
- Research applications: Our work aims to contribute to fields such as computer vision, biometric authentication, and medical imaging

Thank you for your attention to this matter. I appreciate any assistance you can provide in resolving this issue or offering alternative ways to access the dataset. This dataset is vital for benchmarking our algorithms and ensuring our research remains competitive on a global scale.

**Comment by LorenzoAgnolucci** [comment]
Hi @WZUchen 

This repo is related to the paper "**Quality-Aware Image-Text Alignment for Real-World Image Quality Assessment**" and has nothing to do with the Florence 3D Faces Dataset.
