### ISSUE TITLE
Question: How can the model be applied to real-world image quality assessment with images of varying sizes?

### ISSUE THREAD

**Issue by zhengrchan** [miccunifi/QualiCLIP#4]
Hi, I am using the QualiClip model to evaluate real-world images, which typically have high resolutions (700 x 700 +). The aim is to distinguish between high-quality images and those with some degree of compression noise. However, I have found that the model doesn't perform satisfactorily when used directly. How should I employ this model to assess large-sized images with slight noise effectively?

**Comment by LorenzoAgnolucci** [comment]
Hi @zhengrchan!

The experimental results from the paper show that the model can be effectively applied in real-world scenarios. Moreover, images with about 700x700 resolution exist also in the testing datasets. Therefore, I believe that QualiCLIP should obtain satisfactory results. Could you provide some more details on your evaluation protocol? And also, have you tried using some other models to compare the performance, especially CLIP-IQA?
